version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka_producer:
    build: .
    container_name: kafka_producer
    restart: always
    depends_on:
      - kafka
    command: ["python", "kafka_producer.py"]

  event_processor:
    build: .
    container_name: event_processor
    restart: always
    depends_on:
      - kafka
    ports:
      - "5000:5000"
    command: ["python", "event_processor.py"]

  database_connector:
    build: .
    container_name: database_connector
    restart: always
    depends_on:
      - kafka
      - postgres
    command: ["python", "database_connector.py"]

volumes:
  postgres_data:
